"""
Per-source quality filtering of raw JSONL shards.

Filters:
  stack_python   — AST parse check; drop stubs, configs, generated files
  stack_bash     — shebang/command check; drop trivial 1-liners
  stack_md       — English-only (ASCII heuristic); drop template placeholders
  tldr           — passthrough (already clean)
  stackoverflow  — min length + must contain code block
  github_commits — non-trivial commit message + min content length
  github_issues  — min length + not a bot-generated template

Usage:
    python data/pipeline/01_filter.py --source stack_python --in data/raw/ --out data/filtered/
    python data/pipeline/01_filter.py --all --in data/raw/ --out data/filtered/
"""

import argparse
import ast
import json
import re
import sys
from pathlib import Path

from tqdm import tqdm

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

MIN_PYTHON_LINES    = 5       # drop tiny stubs
MAX_PYTHON_LINES    = 2000    # drop pathological files
MIN_BASH_COMMANDS   = 2       # must have at least 2 shell commands
MIN_MD_CHARS        = 200     # drop near-empty markdown
MAX_NON_ASCII_RATIO = 0.05    # >5% non-ASCII → likely non-English
MAX_HTML_DENSITY    = 0.10    # >10% of chars inside HTML tags → HTML blob
MAX_HTML_LINE_RATIO = 0.20    # >20% of lines starting with < → HTML blob
MIN_SO_CHARS        = 300     # Q + A combined
MIN_COMMIT_CHARS    = 128     # new_contents must be substantial
MIN_ISSUE_CHARS     = 200     # full thread

# Patterns indicating generated or template content
GENERATED_PATTERNS = re.compile(
    r"\[\[language\]\]|\[\[version\]\]"       # doc templates
    r"|DO NOT EDIT|AUTO-GENERATED|autogenerated"
    r"|Generated by .{0,40}(swagger|protoc|thrift|avro|django|alembic|sqlalchemy)"
    r"|class Migration\(migrations\.Migration\)",  # Django migrations
    re.IGNORECASE,
)

# Common non-English patterns in YAML frontmatter or opening lines
NON_ENGLISH_MARKERS = re.compile(
    r"^\s*title\s*:.*[^\x00-\x7F]",           # non-ASCII in title field
    re.MULTILINE,
)

# Bash command patterns: lines that look like shell commands
BASH_COMMAND_RE = re.compile(
    r"^\s*(if|for|while|case|echo|export|source|\.|eval|exec|"
    r"cd|ls|cp|mv|rm|mkdir|chmod|chown|find|grep|sed|awk|"
    r"python|python3|pip|npm|yarn|docker|kubectl|git|curl|wget|"
    r"\w+\s+[-\w]|\$\(|\${)",
    re.MULTILINE,
)


# ---------------------------------------------------------------------------
# Filters
# ---------------------------------------------------------------------------

def filter_python(record: dict) -> bool:
    content = record.get("content", "")
    lines = content.splitlines()

    if len(lines) < MIN_PYTHON_LINES or len(lines) > MAX_PYTHON_LINES:
        return False

    # Must parse as valid Python 3
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return False

    # Must have at least one function or class (not just config/data)
    has_code = any(
        isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        for node in ast.walk(tree)
    )
    if not has_code:
        return False

    # Drop generated files
    if GENERATED_PATTERNS.search(content[:2000]):
        return False

    return True


def filter_bash(record: dict) -> bool:
    content = record.get("content", "")

    # Must have at least N shell command patterns
    matches = BASH_COMMAND_RE.findall(content)
    if len(matches) < MIN_BASH_COMMANDS:
        return False

    # Drop generated files
    if GENERATED_PATTERNS.search(content[:500]):
        return False

    return True


def _html_density(text: str) -> float:
    html_chars = sum(len(m.group()) for m in _HTML_TAG_RE.finditer(text))
    return html_chars / max(len(text), 1)

def _html_line_ratio(text: str) -> float:
    lines = [l for l in text.splitlines() if l.strip()]
    if not lines:
        return 0
    return sum(1 for l in lines if l.strip().startswith("<")) / len(lines)


def filter_markdown(record: dict) -> bool:
    content = record.get("content", "")

    if len(content) < MIN_MD_CHARS:
        return False

    # Drop HTML blobs masquerading as markdown
    if _html_density(content) > MAX_HTML_DENSITY:
        return False
    if _html_line_ratio(content) > MAX_HTML_LINE_RATIO:
        return False

    # Drop template placeholders
    if GENERATED_PATTERNS.search(content[:3000]):
        return False

    # Non-English: check non-ASCII ratio in first 1000 chars
    sample = content[:1000]
    non_ascii = sum(1 for c in sample if ord(c) > 127)
    if len(sample) > 0 and non_ascii / len(sample) > MAX_NON_ASCII_RATIO:
        return False

    # Check frontmatter title for non-ASCII
    if NON_ENGLISH_MARKERS.search(content[:500]):
        return False

    # Must contain at least one backtick — proxy for code/technical content
    if "`" not in content:
        return False

    return True


_CODE_BLOCK  = re.compile(r"```|^    \S|\t\S", re.MULTILINE)
_HTML_TAG_RE = re.compile(r"<[^>]+>")

# Stack Overflow: must touch our target domain
# Only unambiguous terms — no short words that collide with natural language
# (dropped: click, arch, fish, sh, helm, sed, awk, gcc, clang, apache)
_SO_TARGET = re.compile(
    r"\b("
    r"python|bash|shell|zsh|"
    r"linux|unix|posix|ubuntu|debian|fedora|centos|"
    r"github|gitlab|"
    r"docker|kubernetes|kubectl|podman|"
    r"pip\b|pipenv|poetry\b|venv|conda|virtualenv|"
    r"flask|django|fastapi|aiohttp|tornado|celery|"
    r"subprocess|multiprocessing|asyncio|"
    r"argparse|typer\b|"
    r"grep|curl\b|wget\b|ssh\b|scp\b|rsync\b|"
    r"cron\b|systemd|supervisord|nginx\b|"
    r"apt-get|brew\b|yum\b|dnf\b|pacman\b|"
    r"makefile|cmake\b|"
    r"re\.compile|regular expression"
    r")\b",
    re.IGNORECASE,
)

_BOT_ISSUE  = re.compile(
    r"(^|\n)(this issue has been automatically|"
    r"this is an? (automated?|bot) (message|comment|report)|"
    r"generated by .{0,30}bot)",
    re.IGNORECASE,
)
_TRIVIAL_COMMIT = re.compile(
    r"^(merge|fix typo|update readme|bump version|wip|minor|cleanup|"
    r"initial commit|first commit|add files|remove files)\.?$",
    re.IGNORECASE,
)


def filter_stackoverflow(record: dict) -> bool:
    content = record.get("content", "")
    if len(content) < MIN_SO_CHARS:
        return False
    # Must contain a code block
    if not _CODE_BLOCK.search(content):
        return False
    # Must touch our target domain — check question only, not the answer
    # (prevents C# questions that mention "bash" in the answer from passing)
    question_part = content.split("\n\nA:")[0]
    if not _SO_TARGET.search(question_part):
        return False
    return True


def filter_github_commits(record: dict) -> bool:
    content = record.get("content", "")
    if len(content) < MIN_COMMIT_CHARS:
        return False
    # First line is the commit message (after stripping "# ")
    first_line = content.partition("\n")[0].lstrip("# ").strip()
    if _TRIVIAL_COMMIT.match(first_line):
        return False
    return True


def filter_github_issues(record: dict) -> bool:
    content = record.get("content", "")
    if len(content) < MIN_ISSUE_CHARS:
        return False
    if GENERATED_PATTERNS.search(content[:500]):
        return False
    if _BOT_ISSUE.search(content[:1000]):
        return False
    # Must touch our target domain (same keyword set as SO)
    if not _SO_TARGET.search(content[:2000]):
        return False
    return True


def filter_tldr(_record: dict) -> bool:
    return True  # already clean


FILTERS = {
    "stack_python":   filter_python,
    "stack_bash":     filter_bash,
    "stack_md":       filter_markdown,
    "stackoverflow":  filter_stackoverflow,
    "github_commits": filter_github_commits,
    "github_issues":  filter_github_issues,
    "tldr":           filter_tldr,
}


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

def filter_source(source: str, in_dir: Path, out_dir: Path):
    filter_fn = FILTERS[source]
    in_shards = sorted(in_dir.glob(f"{source}_*.jsonl"))
    if not in_shards:
        print(f"  {source}: no input shards found in {in_dir}")
        return

    kept = 0
    total = 0

    out_path = out_dir / f"{source}.jsonl"
    with open(out_path, "w") as out_f:
        for shard in in_shards:
            with open(shard) as f:
                for line in tqdm(f, desc=f"{source} ({shard.name})", unit="rec"):
                    total += 1
                    try:
                        record = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if filter_fn(record):
                        out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
                        kept += 1

    pct = 100 * kept / max(total, 1)
    print(f"  {source}: {kept:,} / {total:,} kept ({pct:.1f}%) → {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Filter raw corpus shards")
    parser.add_argument("--in", dest="in_dir", required=True, help="Directory with raw JSONL shards")
    parser.add_argument("--out", required=True, help="Output directory for filtered JSONL")
    parser.add_argument("--source", choices=list(FILTERS), help="Single source to filter")
    parser.add_argument("--all", action="store_true", help="Filter all sources")
    args = parser.parse_args()

    in_dir = Path(args.in_dir)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.all:
        sources = list(FILTERS)
    elif args.source:
        sources = [args.source]
    else:
        parser.print_help()
        sys.exit(1)

    for source in sources:
        filter_source(source, in_dir, out_dir)


if __name__ == "__main__":
    main()
