"""
DataTrove-based corpus pipeline: download + filter in one pass, per source.

Replaces 00_download.py + 01_filter.py + 02_dedup.py.
Resumable: completed shards tracked in --logs dir; re-run to continue.

Usage:
    # Single source (experiment scale — capped):
    python data/pipeline/pipeline.py --source stack_python --out data/processed/

    # All sources, full scale, 16 workers:
    python data/pipeline/pipeline.py --all --full --workers 16 --out data/processed/

    # Resume an interrupted run (same command, picks up where it left off):
    python data/pipeline/pipeline.py --source stack_python --out data/processed/

Output:
    data/processed/<source>/<shard>.jsonl.gz  — one file per shard, resumable
"""

import argparse
import ast
import re
import sys
from pathlib import Path

from datatrove.executor import LocalPipelineExecutor
from datatrove.pipeline.readers import HuggingFaceDatasetReader, JsonlReader
from datatrove.pipeline.writers import JsonlWriter
from datatrove.pipeline.filters.base_filter import BaseFilter
from datatrove.data import Document


# ── constants ─────────────────────────────────────────────────────────────────

MAX_FILE_BYTES = 1_000_000  # 1MB — skip pathological files

PERMISSIVE_LICENSES = {
    "MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause",
    "ISC", "Unlicense", "CC0-1.0", "WTFPL", "0BSD",
    "BSD-4-Clause", "AFL-3.0", "ECL-2.0",
}

# Experiment-scale caps (number of documents, not tokens)
EXPERIMENT_CAPS = {
    "stack_python":   1_000_000,
    "stack_bash":       250_000,
    "stack_md":         200_000,
    "stackoverflow":    600_000,
    "github_commits":   200_000,
    "github_issues":    150_000,
    "tldr":            None,   # small enough to always run in full
}


# ── filter logic (ported from 01_filter.py) ──────────────────────────────────

_GENERATED = re.compile(
    r"\[\[language\]\]|\[\[version\]\]"
    r"|DO NOT EDIT|AUTO-GENERATED|autogenerated"
    r"|Generated by .{0,40}(swagger|protoc|thrift|avro|django|alembic|sqlalchemy)"
    r"|class Migration\(migrations\.Migration\)",
    re.IGNORECASE,
)
_BASH_CMD = re.compile(
    r"^\s*(if|for|while|case|echo|export|source|\.|eval|exec|"
    r"cd|ls|cp|mv|rm|mkdir|chmod|chown|find|grep|sed|awk|"
    r"python|python3|pip|npm|yarn|docker|kubectl|git|curl|wget|"
    r"\w+\s+[-\w]|\$\(|\${)",
    re.MULTILINE,
)
_HTML_TAG = re.compile(r"<[^>]+>")
_CODE_BLOCK = re.compile(r"```|^    \S|\t\S", re.MULTILINE)
_SO_TARGET = re.compile(
    r"\b(python|bash|shell|zsh|linux|unix|posix|ubuntu|debian|fedora|centos|"
    r"github|gitlab|docker|kubernetes|kubectl|podman|"
    r"pip\b|pipenv|poetry\b|venv|conda|virtualenv|"
    r"flask|django|fastapi|aiohttp|tornado|celery|"
    r"subprocess|multiprocessing|asyncio|argparse|typer\b|"
    r"grep|curl\b|wget\b|ssh\b|scp\b|rsync\b|"
    r"cron\b|systemd|supervisord|nginx\b|"
    r"apt-get|brew\b|yum\b|dnf\b|pacman\b|"
    r"makefile|cmake\b|re\.compile|regular expression)\b",
    re.IGNORECASE,
)
_BOT_ISSUE = re.compile(
    r"(^|\n)(this issue has been automatically|"
    r"this is an? (automated?|bot) (message|comment|report)|"
    r"generated by .{0,30}bot)",
    re.IGNORECASE,
)
_TRIVIAL_COMMIT = re.compile(
    r"^(merge|fix typo|update readme|bump version|wip|minor|cleanup|"
    r"initial commit|first commit|add files|remove files)\.?$",
    re.IGNORECASE,
)
_NON_ASCII_TITLE = re.compile(r"^\s*title\s*:.*[^\x00-\x7F]", re.MULTILINE)


class StackPythonFilter(BaseFilter):
    name = "Stack Python Filter"

    def filter(self, doc: Document):
        text = doc.text
        lines = text.splitlines()
        if not (5 <= len(lines) <= 2000):
            return False, "line count"
        if len(text) > 200_000:
            return False, "too large"
        try:
            tree = ast.parse(text)
        except (SyntaxError, RecursionError, MemoryError):
            return False, "syntax error"
        has_def = any(
            isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            for n in ast.walk(tree)
        )
        if not has_def:
            return False, "no def/class"
        if _GENERATED.search(text[:2000]):
            return False, "generated"
        return True


class StackBashFilter(BaseFilter):
    name = "Stack Bash Filter"

    def filter(self, doc: Document):
        text = doc.text
        if len(_BASH_CMD.findall(text)) < 2:
            return False, "too few commands"
        if _GENERATED.search(text[:500]):
            return False, "generated"
        return True


class StackMarkdownFilter(BaseFilter):
    name = "Stack Markdown Filter"

    def filter(self, doc: Document):
        text = doc.text
        if len(text) < 200:
            return False, "too short"
        html_chars = sum(len(m.group()) for m in _HTML_TAG.finditer(text))
        if html_chars / max(len(text), 1) > 0.10:
            return False, "html blob"
        lines = [l for l in text.splitlines() if l.strip()]
        if lines and sum(1 for l in lines if l.strip().startswith("<")) / len(lines) > 0.20:
            return False, "html lines"
        if _GENERATED.search(text[:3000]):
            return False, "generated"
        sample = text[:1000]
        if sample and sum(1 for c in sample if ord(c) > 127) / len(sample) > 0.05:
            return False, "non-english"
        if _NON_ASCII_TITLE.search(text[:500]):
            return False, "non-english title"
        if "`" not in text:
            return False, "no code"
        return True


class StackOverflowFilter(BaseFilter):
    name = "Stack Overflow Filter"

    def filter(self, doc: Document):
        text = doc.text
        if len(text) < 300:
            return False, "too short"
        if not _CODE_BLOCK.search(text):
            return False, "no code block"
        question_part = text.split("\n\nA:")[0]
        if not _SO_TARGET.search(question_part):
            return False, "off topic"
        return True


class GitHubCommitsFilter(BaseFilter):
    name = "GitHub Commits Filter"

    def filter(self, doc: Document):
        text = doc.text
        if len(text) < 128:
            return False, "too short"
        first_line = text.partition("\n")[0].lstrip("# ").strip()
        if _TRIVIAL_COMMIT.match(first_line):
            return False, "trivial commit"
        return True


class GitHubIssuesFilter(BaseFilter):
    name = "GitHub Issues Filter"

    def filter(self, doc: Document):
        text = doc.text
        if len(text) < 200:
            return False, "too short"
        if _GENERATED.search(text[:500]):
            return False, "generated"
        if _BOT_ISSUE.search(text[:1000]):
            return False, "bot issue"
        if not _SO_TARGET.search(text[:2000]):
            return False, "off topic"
        return True


# ── license filter for Stack sources ─────────────────────────────────────────

class StackLicenseFilter(BaseFilter):
    """Keep only files with permissive licenses and reasonable size."""
    name = "Stack License Filter"

    def filter(self, doc: Document):
        licenses = doc.metadata.get("licenses") or []
        if isinstance(licenses, str):
            licenses = [licenses]
        if not any(lic in PERMISSIVE_LICENSES for lic in licenses):
            return False, "license"
        if not doc.text or len(doc.text) > MAX_FILE_BYTES or len(doc.text) < 64:
            return False, "size"
        return True


# ── pipeline builders ─────────────────────────────────────────────────────────

def _stack_adapter(self, data: dict, path: str, id_in_file: int) -> dict | None:
    content = data.get("content") or ""
    if not content:
        return None
    licenses = (
        data.get("max_stars_repo_licenses")
        or data.get("max_issues_repo_licenses")
        or data.get("max_forks_repo_licenses")
        or []
    )
    return {
        "text": content,
        "id":   data.get("hexsha") or f"{path}/{id_in_file}",
        "metadata": {
            "licenses": licenses,
            "path": data.get("max_stars_repo_path", ""),
            "lang": data.get("lang", ""),
        },
    }


def _stack_pipeline(lang: str, source: str, out_dir: Path, full: bool, workers: int, logs: Path, limit_override=None):
    data_dir = {"python": "data/python", "shell": "data/shell", "markdown": "data/markdown"}[lang]
    cap = limit_override if limit_override is not None else (None if full else EXPERIMENT_CAPS[source])
    limit = cap if cap is not None else -1
    filter_cls = {"python": StackPythonFilter, "shell": StackBashFilter, "markdown": StackMarkdownFilter}[lang]

    pipeline = [
        HuggingFaceDatasetReader(
            dataset="bigcode/the-stack-dedup",
            dataset_options={"data_dir": data_dir, "split": "train"},
            adapter=_stack_adapter,
            streaming=True,
            limit=limit,
        ),
        StackLicenseFilter(),
        filter_cls(),
        JsonlWriter(output_folder=str(out_dir / source)),
    ]
    return LocalPipelineExecutor(pipeline=pipeline, tasks=workers, logging_dir=str(logs / source))


def _so_adapter(self, data: dict, path: str, id_in_file: int) -> dict | None:
    return {
        "text": data.get("question") or "",
        "id":   str(id_in_file),
        "metadata": {"answers": data.get("answers") or []},
    }


def _stackoverflow_pipeline(out_dir: Path, full: bool, workers: int, logs: Path, limit_override=None):
    cap = limit_override if limit_override is not None else (None if full else EXPERIMENT_CAPS["stackoverflow"])
    limit = cap if cap is not None else -1
    pipeline = [
        HuggingFaceDatasetReader(
            dataset="HuggingFaceH4/stack-exchange-preferences",
            dataset_options={"split": "train"},
            adapter=_so_adapter,
            streaming=True,
            limit=limit,
        ),
        # Format Q+A and filter in one custom step
        _SOFormatter(),
        StackOverflowFilter(),
        JsonlWriter(output_folder=str(out_dir / "stackoverflow")),
    ]
    return LocalPipelineExecutor(pipeline=pipeline, tasks=workers, logging_dir=str(logs / "stackoverflow"))


_HTML_TAG_RE  = re.compile(r"<[^>]+>")
_HTML_ENT_RE  = re.compile(r"&(amp|lt|gt|quot|apos|nbsp|#\d+|#x[0-9a-fA-F]+);")
_ENTITY_MAP   = {"amp": "&", "lt": "<", "gt": ">", "quot": '"', "apos": "'", "nbsp": " "}

def _strip_html(text: str) -> str:
    text = _HTML_TAG_RE.sub("", text)
    def _ent(m):
        name = m.group(1)
        if name in _ENTITY_MAP: return _ENTITY_MAP[name]
        if name.startswith("#x"): return chr(int(name[2:], 16))
        if name.startswith("#"):  return chr(int(name[1:]))
        return " "
    return _HTML_ENT_RE.sub(_ent, text).strip()


class _SOFormatter(BaseFilter):
    """Strip HTML, combine question + best answer into a single text field."""
    name = "SO Formatter"

    def filter(self, doc: Document):
        answers = doc.metadata.get("answers") or []
        if not answers:
            return False, "no answers"
        best = max(answers, key=lambda a: (a.get("selected", False), a.get("pm_score", 0)))
        answer = _strip_html(best.get("text", "")).strip()
        if len(answer) < 100:
            return False, "short answer"
        question = _strip_html(doc.text)
        doc.text = f"Q: {question}\n\nA: {answer}"
        return True


def _commits_adapter(self, data: dict, path: str, id_in_file: int) -> dict | None:
    return {
        "text": data.get("new_contents") or "",
        "id":   str(id_in_file),
        "metadata": {
            "subject": data.get("subject") or "",
            "lang":    data.get("lang") or "",
            "license": data.get("license") or "",
        },
    }


def _github_commits_pipeline(out_dir: Path, full: bool, workers: int, logs: Path, limit_override=None):
    cap = limit_override if limit_override is not None else (None if full else EXPERIMENT_CAPS["github_commits"])
    limit = cap if cap is not None else -1
    pipeline = [
        HuggingFaceDatasetReader(
            dataset="json",
            dataset_options={
                "data_files": {
                    "train": [
                        "hf://datasets/bigcode/commitpackft/data/python/data.jsonl",
                        "hf://datasets/bigcode/commitpackft/data/shell/data.jsonl",
                    ]
                },
                "split": "train",
            },
            adapter=_commits_adapter,
            streaming=True,
            limit=limit,
        ),
        _CommitFormatter(),
        GitHubCommitsFilter(),
        JsonlWriter(output_folder=str(out_dir / "github_commits")),
    ]
    return LocalPipelineExecutor(pipeline=pipeline, tasks=workers, logging_dir=str(logs / "github_commits"))


class _CommitFormatter(BaseFilter):
    """Prepend commit message as a comment."""
    name = "Commit Formatter"
    _TRIVIAL = re.compile(
        r"^(merge|fix typo|update readme|bump version|wip|minor|cleanup|"
        r"initial commit|first commit|add files|remove files)\.?$",
        re.IGNORECASE,
    )

    def filter(self, doc: Document):
        subject = (doc.metadata.get("subject") or "").strip()
        if not subject or self._TRIVIAL.match(subject):
            return False, "trivial"
        if not doc.text:
            return False, "empty"
        doc.text = f"# {subject}\n\n{doc.text[:MAX_FILE_BYTES]}"
        return True


def _issues_adapter(self, data: dict, path: str, id_in_file: int) -> dict | None:
    return {
        "text": data.get("content") or "",
        "id":   str(id_in_file),
        "metadata": {
            "repo":         data.get("repo") or "",
            "text_size":    data.get("text_size") or 0,
            "pull_request": data.get("pull_request") or False,
        },
    }


def _github_issues_pipeline(out_dir: Path, full: bool, workers: int, logs: Path, limit_override=None):
    cap = limit_override if limit_override is not None else (None if full else EXPERIMENT_CAPS["github_issues"])
    limit = cap if cap is not None else -1
    pipeline = [
        HuggingFaceDatasetReader(
            dataset="bigcode/the-stack-github-issues",
            dataset_options={"split": "train"},
            adapter=_issues_adapter,
            streaming=True,
            limit=limit,
        ),
        _IssueFormatter(),
        GitHubIssuesFilter(),
        JsonlWriter(output_folder=str(out_dir / "github_issues")),
    ]
    return LocalPipelineExecutor(pipeline=pipeline, tasks=workers, logging_dir=str(logs / "github_issues"))


class _IssueFormatter(BaseFilter):
    name = "Issue Formatter"
    _TOKENS = re.compile(r"<issue_start>|<issue_comment>|<issue_closed>|<issue_opened>")

    def filter(self, doc: Document):
        if doc.metadata.get("pull_request"):
            return False, "pull request"
        if (doc.metadata.get("text_size") or 0) < 200:
            return False, "too short"
        doc.text = self._TOKENS.sub("\n---\n", doc.text).strip()[:MAX_FILE_BYTES]
        return True


def _tldr_pipeline(out_dir: Path, logs: Path):
    """tldr-pages: read from a cloned repo directory."""
    pipeline = [
        JsonlWriter(output_folder=str(out_dir / "tldr")),
    ]
    # tldr is tiny — handled separately (git clone + direct read)
    print("tldr: clone https://github.com/tldr-pages/tldr and run 05_tokenize.py directly.")


# ── CLI ───────────────────────────────────────────────────────────────────────

ALL_SOURCES = ["stack_python", "stack_bash", "stack_md", "stackoverflow", "github_commits", "github_issues"]

def main():
    parser = argparse.ArgumentParser(description="DataTrove corpus pipeline: download + filter")
    parser.add_argument("--out",     required=True, help="Output directory for processed JSONL shards")
    parser.add_argument("--logs",    default="logs/pipeline", help="DataTrove logging/resumability dir")
    parser.add_argument("--source",  choices=ALL_SOURCES, action="append", dest="sources",
                        help="Source to process (repeatable: --source stack_python --source stack_bash)")
    parser.add_argument("--all",     action="store_true", help="All sources")
    parser.add_argument("--full",    action="store_true", help="Full scale (no caps)")
    parser.add_argument("--limit",   type=int, default=None,
                        help="Override cap for quick tests (e.g. --limit 1000)")
    parser.add_argument("--workers", type=int, default=8, help="Parallel workers per source (default 8)")
    args = parser.parse_args()

    out_dir  = Path(args.out)
    logs_dir = Path(args.logs)
    out_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    sources = ALL_SOURCES if args.all else (args.sources or [])
    if not sources:
        parser.print_help()
        sys.exit(1)

    for source in sources:
        print(f"\n{'='*60}\n{source}  (full={args.full}, workers={args.workers})\n{'='*60}")
        if source == "stack_python":
            executor = _stack_pipeline("python", source, out_dir, args.full, args.workers, logs_dir, args.limit)
        elif source == "stack_bash":
            executor = _stack_pipeline("shell", source, out_dir, args.full, args.workers, logs_dir, args.limit)
        elif source == "stack_md":
            executor = _stack_pipeline("markdown", source, out_dir, args.full, args.workers, logs_dir, args.limit)
        elif source == "stackoverflow":
            executor = _stackoverflow_pipeline(out_dir, args.full, args.workers, logs_dir, args.limit)
        elif source == "github_commits":
            executor = _github_commits_pipeline(out_dir, args.full, args.workers, logs_dir, args.limit)
        elif source == "github_issues":
            executor = _github_issues_pipeline(out_dir, args.full, args.workers, logs_dir, args.limit)
        else:
            print(f"  {source}: not yet implemented")
            continue
        executor.run()


if __name__ == "__main__":
    main()
